name: Docker

on:
  push:
    branches: ["**"]
    paths:
      - "infra/**"
      - "services/**"
      - "core-engine/**"
      - "sdk/**"
      - "programs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/docker.yml"
  pull_request:
    branches: ["**"]
    paths:
      - "infra/**"
      - "services/**"
      - "core-engine/**"
      - "sdk/**"
      - "programs/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - ".github/workflows/docker.yml"
  workflow_dispatch:
    inputs:
      push_images:
        description: "Push images to registry (requires secrets)."
        type: boolean
        default: false
      registry:
        description: "Container registry (e.g. ghcr.io/<owner>)"
        type: string
        default: "ghcr.io/${{ github.repository_owner }}"
      tag:
        description: "Image tag (default: sha)"
        type: string
        default: ""

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  DOCKER_BUILDKIT: "1"
  NODE_VERSION: "20"
  PYTHON_VERSION: "3.12"
  SOLANA_VERSION: "v1.18.26"
  ANCHOR_VERSION: "0.30.1"

jobs:
  detect:
    name: Detect Docker build targets
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
      any: ${{ steps.set.outputs.any }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build matrix from infra/docker/images
        id: set
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -d "infra/docker/images" ]; then
            echo "any=false" >> "$GITHUB_OUTPUT"
            echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
            echo "infra/docker/images not found"
            exit 0
          fi

          mapfile -t files < <(ls -1 infra/docker/images/*.Dockerfile 2>/dev/null | sort || true)
          if [ "${#files[@]}" -eq 0 ]; then
            echo "any=false" >> "$GITHUB_OUTPUT"
            echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
            echo "No Dockerfiles found under infra/docker/images"
            exit 0
          fi

          json='{"include":['
          first=1
          for f in "${files[@]}"; do
            base="$(basename "$f")"                 # e.g., engine.Dockerfile
            name="${base%.Dockerfile}"              # engine
            if [ $first -eq 1 ]; then first=0; else json+=','; fi
            json+="{\"dockerfile\":\"$f\",\"name\":\"$name\"}"
          done
          json+=']}'

          echo "any=true" >> "$GITHUB_OUTPUT"
          echo "matrix=$json" >> "$GITHUB_OUTPUT"

          echo "Detected Docker targets:"
          printf ' - %s\n' "${files[@]}"

  build:
    name: Build (${{ matrix.name }})
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.any == 'true' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: tag
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.tag || '' }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_SHA}"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Compute image names
        id: img
        shell: bash
        run: |
          set -euo pipefail
          REGISTRY="${{ github.event.inputs.registry || format('ghcr.io/{0}', github.repository_owner) }}"
          IMAGE="${REGISTRY}/m0club-${{ matrix.name }}"
          echo "registry=$REGISTRY" >> "$GITHUB_OUTPUT"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (only if pushing)
        if: ${{ github.event.inputs.push_images == true }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.img.outputs.image }}
          tags: |
            type=raw,value=${{ steps.tag.outputs.tag }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build (and optionally push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event.inputs.push_images == true }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable cross-step caching
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_VERSION=${{ env.NODE_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            SOLANA_VERSION=${{ env.SOLANA_VERSION }}
            ANCHOR_VERSION=${{ env.ANCHOR_VERSION }}

      - name: Save image as tar (for PR debugging)
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.push_images != true }}
        shell: bash
        run: |
          set -euo pipefail
          # Save the first tag to a tarball to allow optional download
          first_tag="$(echo '${{ steps.meta.outputs.tags }}' | head -n1)"
          if [ -z "$first_tag" ]; then
            echo "No tags produced"
            exit 0
          fi
          docker pull "$first_tag" || true
          mkdir -p artifacts/images
          safe="${{ matrix.name }}-${{ steps.tag.outputs.tag }}"
          docker save "$first_tag" -o "artifacts/images/${safe}.tar" || true

      - name: Upload image tarball artifact
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.push_images != true }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ matrix.name }}
          path: artifacts/images/*.tar
          if-no-files-found: ignore
          retention-days: 7

  compose-smoke:
    name: Compose smoke test (optional)
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check compose file
        id: compose
        shell: bash
        run: |
          set -euo pipefail
          if [ -f "infra/docker/compose.dev.yml" ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Docker compose config
        if: ${{ steps.compose.outputs.has == 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          docker compose -f infra/docker/compose.dev.yml config

      - name: Docker compose up (short)
        if: ${{ steps.compose.outputs.has == 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          docker compose -f infra/docker/compose.dev.yml up -d --build
          docker compose -f infra/docker/compose.dev.yml ps
          # Allow a short startup window, then exit
          sleep 15
          docker compose -f infra/docker/compose.dev.yml logs --no-color --tail=200 || true

      - name: Docker compose down
        if: ${{ steps.compose.outputs.has == 'true' }}
        shell: bash
        run: |
          set -euo pipefail
          docker compose -f infra/docker/compose.dev.yml down -v

  security:
    name: Container-related security checks (OSV)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OSV-Scanner (repo)
        uses: google/osv-scanner-action@v1.7.3
        with:
          scan-args: |-
            --recursive
            --skip-git
            .

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif
          category: osv
